import React from "react";
export const productsList: any = {
    ids: [
        {
            name: "4 Days 3 Nights Jaipur Ranthambore Tour",
            slug: "jaipur-ranthambore-tour",
            state: "published",
            product_type: "tour",
            strike_through_price: 6000,
            starting_price: 5000,
            least_priced_inventory: "Adult",
            primary_destination: "Jaipur",
            featured_image_urls: {
                original:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,q_auto/v1/filestore/o398xvox63cvs3umcicf5oiisg0n_things-to-do-in-ranthambore-tiger.jpg",
                thumbnail:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,h_300,q_auto,w_400/v1/filestore/o398xvox63cvs3umcicf5oiisg0n_things-to-do-in-ranthambore-tiger.jpg",
            },
            rating: 4.5,
            id: 72629,
            reviews_count: 34,
            actual_review_count: 0,
            updated_at: "2023-02-18T02:20:44.549Z",
            created_at: "2022-05-15T22:42:24.844Z",
            code: "PRDXaCX6NB04c",
            currency: "INR",
            owner: {
                id: 2,
                created_at: "2022-05-09T11:53:08.069Z",
                updated_at: "2023-01-20T15:48:59.497Z",
                company_name: "53 Take offs",
                subdomain: "53takeoffs",
                cname: null,
                company_phone: "9916134180",
                company_phone_country_code: "+91",
                company_email: "info+53takeoff@thrillophilia.com",
                is_thrillophilia_entity: true,
                currency: "INR",
                can_have_website: false,
            },
            resellers: [
                {
                    id: 1,
                    created_at: "2020-08-17T14:00:11.486Z",
                    updated_at: "2022-05-17T05:17:14.669Z",
                    company_name: "Thrillophilia",
                    subdomain: "www",
                    cname: "www.thrillophilia.com",
                    company_phone: "9916134180",
                    company_phone_country_code: "+91",
                    company_email: "info@thrillophilia.com",
                    is_thrillophilia_entity: true,
                    currency: "INR",
                    can_have_website: false,
                },
            ],
            is_current_partner_product: false,
            partner_name: "53 Take offs",
            partner_product_state: "active",
            storefront_url:
                "https://www.thrillophilia.com/tours/jaipur-ranthambore-tour",
            shared_with_partners: 1,
            accepted_partners: 1,
            pending_partners: 0,
        },
        {
            name: "WTF Sports Lounge Tickets",
            slug: "wtf-club-tickets",
            state: "published",
            product_type: "activity",
            strike_through_price: 550.01,
            starting_price: 550,
            least_priced_inventory: "Adult",
            primary_destination: "Jaipur",
            featured_image_urls: {
                original:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,q_auto/v1/filestore/sbm5d29qs6qhgplw0vhw09taqmwk_the-great-kabab-factory-radisson-jaipur-city-center--m-i-road-jaipur-north-indian-restaurants-h66oavtsad.jpg",
                thumbnail:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,h_300,q_auto,w_400/v1/filestore/sbm5d29qs6qhgplw0vhw09taqmwk_the-great-kabab-factory-radisson-jaipur-city-center--m-i-road-jaipur-north-indian-restaurants-h66oavtsad.jpg",
            },
            rating: 4.5,
            id: 108608,
            reviews_count: 27,
            actual_review_count: 0,
            updated_at: "2023-02-18T02:50:55.707Z",
            created_at: "2022-11-08T10:25:17.859Z",
            code: "PRDM8r5jyXuKz",
            currency: "INR",
            owner: {
                id: 1,
                created_at: "2020-08-17T14:00:11.486Z",
                updated_at: "2022-05-17T05:17:14.669Z",
                company_name: "Thrillophilia",
                subdomain: "www",
                cname: "www.thrillophilia.com",
                company_phone: "9916134180",
                company_phone_country_code: "+91",
                company_email: "info@thrillophilia.com",
                is_thrillophilia_entity: true,
                currency: "INR",
                can_have_website: false,
            },
            resellers: [],
            is_current_partner_product: true,
            partner_name: "Thrillophilia",
            storefront_url: "https://www.thrillophilia.com/tours/wtf-club-tickets",
        },
        {
            name: "Ranthambore National Park Safari",
            slug: "jaipur-to-ranthambore-tour",
            state: "published",
            product_type: "tour",
            strike_through_price: 4000,
            starting_price: 2200,
            least_priced_inventory: "Adult",
            primary_destination: "Jaipur",
            featured_image_urls: {
                original:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,q_auto/v1/filestore/wieaf3z0ufe6n4gbv5fuut8o3c5x_3.jpg",
                thumbnail:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,h_300,q_auto,w_400/v1/filestore/wieaf3z0ufe6n4gbv5fuut8o3c5x_3.jpg",
            },
            rating: 4.5,
            id: 109303,
            reviews_count: 38,
            actual_review_count: 0,
            updated_at: "2023-02-18T02:51:52.346Z",
            created_at: "2022-11-10T12:10:19.845Z",
            code: "PRDZvMMamzb2r",
            currency: "INR",
            owner: {
                id: 1,
                created_at: "2020-08-17T14:00:11.486Z",
                updated_at: "2022-05-17T05:17:14.669Z",
                company_name: "Thrillophilia",
                subdomain: "www",
                cname: "www.thrillophilia.com",
                company_phone: "9916134180",
                company_phone_country_code: "+91",
                company_email: "info@thrillophilia.com",
                is_thrillophilia_entity: true,
                currency: "INR",
                can_have_website: false,
            },
            resellers: [],
            is_current_partner_product: true,
            partner_name: "Thrillophilia",
            storefront_url:
                "https://www.thrillophilia.com/tours/jaipur-to-ranthambore-tour",
        },
        {
            name: "Jaipur Jodhpur Jaisalmer | Bestseller Rajasthan Tour Package",
            slug: "bestseller-rajasthan-tour",
            state: "published",
            product_type: "tour",
            strike_through_price: 22100,
            starting_price: 15199,
            least_priced_inventory: "Adult",
            primary_destination: "Jaipur",
            featured_image_urls: {
                original:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,q_auto/v1/filestore/rmapgr8eol0ix98w5akzp8474eem_%5BDownloader.la%5D-630ddd1fb215e.jpg",
                thumbnail:
                    "https://res.cloudinary.com/thrillophilia/image/upload/c_fill,f_auto,fl_progressive.strip_profile,g_auto,h_300,q_auto,w_400/v1/filestore/rmapgr8eol0ix98w5akzp8474eem_%5BDownloader.la%5D-630ddd1fb215e.jpg",
            },
            rating: 4.5,
            id: 93636,
            reviews_count: 27,
            actual_review_count: 0,
            updated_at: "2023-02-07T02:23:52.728Z",
            created_at: "2022-08-25T07:26:43.994Z",
            code: "PRDTvDkbsC2KW",
            currency: "INR",
            owner: {
                id: 2,
                created_at: "2022-05-09T11:53:08.069Z",
                updated_at: "2023-01-20T15:48:59.497Z",
                company_name: "53 Take offs",
                subdomain: "53takeoffs",
                cname: null,
                company_phone: "9916134180",
                company_phone_country_code: "+91",
                company_email: "info+53takeoff@thrillophilia.com",
                is_thrillophilia_entity: true,
                currency: "INR",
                can_have_website: false,
            },
            resellers: [
                {
                    id: 1,
                    created_at: "2020-08-17T14:00:11.486Z",
                    updated_at: "2022-05-17T05:17:14.669Z",
                    company_name: "Thrillophilia",
                    subdomain: "www",
                    cname: "www.thrillophilia.com",
                    company_phone: "9916134180",
                    company_phone_country_code: "+91",
                    company_email: "info@thrillophilia.com",
                    is_thrillophilia_entity: true,
                    currency: "INR",
                    can_have_website: false,
                },
            ],
            is_current_partner_product: false,
            partner_name: "53 Take offs",
            partner_product_state: "active",
            storefront_url:
                "https://www.thrillophilia.com/tours/bestseller-rajasthan-tour",
            shared_with_partners: 1,
            accepted_partners: 1,
            pending_partners: 0,
        },
    ],
};